### ISSUE TITLE
Add more architectures to Actions

### ISSUE THREAD

**Issue by dartzcn** [computernewb/collab-vm-server#117] opened 2022-01-08 21:36 UTC
This Action: https://github.com/uraimo/run-on-arch-action can produce builds for armv6, armv7, aarch64, s390x, and ppc64le. ARM and AArch64 would be ideal targets in addition to amd64.

**Comment by yellows111** [comment] 2022-01-08 21:39
(some semi-obvious joke about how many people ask us if we support i386)
Agreed on supporting RISC targets for this, as those are becoming more common as time passes.

**Comment by modeco80** [comment] 2022-01-08 21:42
we can just cross compile i think
tbh if it wasn't dll hell worthy I'd maybe think about a "collabvm runtime libraries" thing which everyone (including plugins) links to, which contains agreed (and hotfixed if required) versions of:

- glibc/libstdc++/libc++ for LLVM
- Boost
- Any additional dependencies we may need along the line
- (for developers) gcc/clang

advantages are:
 - we can just set the runpath to ./runtime or whatever
 - runs on any distro uniformly (since theres no needed libraries from the distro)
 - user doesn't need to install any packages
 - we can subset libraries (i.e: we really only need a couple binary boost libraries atm), reducing dist space
 

drawbacks:
 - as fore-mentioned, dll hell
 - may cause dist issues?
 - can't do something like this for windows although msvc ab(+ p?)i seems stable enough
 - package management will suck (although I guess we can provide a way to use system libs. plugins would have to be rebuilt if they are too old for the system glibc or something though)

**Comment by modeco80** [comment] 2022-01-08 21:55
actually thinking about it ^ seems like the best way to handle stuff, so i may do it

**Comment by modeco80** [comment] 2022-01-08 22:25
test

**Comment by dakrk** [comment] 2022-01-08 22:25
so true

**Comment by modeco80** [comment] 2022-03-12 01:58
another actually: i've decided that vendoring libs is probably not the greatest idea..

For plugins I'm allowing a vendored eastl/EAStdC/EABase/EAAssert/EAThread (yeah.. it pulls in quite the dependency chain lmao) which on install will be shipped in `/usr/lib/collabvm`, along with a different name `libcollabvm-eastl`, such... This should ease the headaches of any package maintainers and allow us to use modern C++ and the stl cross boundaries.

**Comment by modeco80** [comment] 2022-12-11 09:45
Actually 3.14: I'm considering just using conan for everything, especially when 2.0 comes out

there's other things like CPM or hunter but ehhhh

**Comment by modeco80** [comment] 2023-03-20 10:18
Actually 3.20: Closing for now (until i have enough scaffolding ready to try tackling this), but here are some notes, mostly plagarized from [the rustup book](https://rust-lang.github.io/rustup/cross-compilation.html):

`rustup target add [--toolchain <toolchain>] <triplet>` allows us to add a target triplet to either the default toolchain or an explicitly specified one

we can then build with `cargo build --target <triplet>` (incl `--release` if desired) to cross compile. this is all handled in cargo which I actually find pretty nice (well, it's not something we have to explicitly mess with for the most part, so it's a little less of a pain. better than no change ig)

using GH actions support for spawning inside of a Docker container (which I've previously used because devkitpro devs are overzealous as all hell and force people to use said images, blocking git(hub|lab) ips from even reaching their package servers..) we can also build separate images for each triplet we want to explicitly support, and use those to build, but that seems a little messy (though it IS a bit more reproducible, I suppose)

Note that we WILL have to use rustup then in order to actually get Rust, which... is probably a good idea anyways.

**Closed as completed by modeco80** 2023-03-20 10:18 UTC
Labels: enhancement, server, server/vm
